### ISSUE TITLE
When the output formatter is used, and there are 

### ISSUE THREAD

**Issue by salimfadhley** [aroden-crowdstrike/pylint2junit#1]
In the scenario where there are no lint errors:
```
pylint helloworld --output-format=pylint2junit.JunitReporter > pylint.xml
```
We might expect the pylint.xml file to contain valid XML containing zero errors, however, what actually happens is that it's a zero bytes long file.

**Comment by rasjani** [comment]
Had to get a quick fix for a project im working on and fixed with this: https://github.com/rasjani/pylint2junit/commit/ffd6a9dad75fadf08d1f532c136bc37fc7113314

A Very Hackish way but works for me at the moment ..

**Comment by aroden-crowdstrike** [comment]
Thank you! Looks good to me
